[package]
name = "launcher_web_deploy"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../../.."
edition = "2021"
publish = false

[lib]
name = "launcher"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
local = [ "launcher_app/local" ]
prod = [ "launcher_app/prod" ]
gl_renderer = [ "launcher_app/gl_renderer" ]
wgpu_renderer = [ "launcher_app/wgpu_renderer" ]

[dependencies]
kernel = { path = "../../../crates/kernel" }
logging = { path = "../../../crates/logging" }
launcher_app = { path = "../../../apps/launcher" }

cfg-if = { version = "1.0" }

wasm-bindgen = { version = "0.2", features = [ "serde-serialize" ] }
wasm-bindgen-futures = { version = "0.4.40" }