[package]
name = "session_server"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = "../.."
edition = "2021"
publish = false

[features]
local = [ "config/local", "session_server_naia_proto/local" ]
prod = [ "config/prod", "session_server_naia_proto/prod" ]
odst = [ "config/odst" ]

[dependencies]
naia-bevy-server = { path = "../../../naia/adapters/bevy/server", features = [ "transport_webrtc" ] }
bevy_http_server = { path = "../../crates/http/bevy_http_server" }
bevy_http_client = { path = "../../crates/http/bevy_http_client" }
config = { path = "../../config", features = ["session"] }
crypto = { path = "../../crates/crypto" }
asset_id = { path = "../../crates/asset/id" }
random = { path = "../../crates/random" }
logging = { path = "../../crates/logging" }
auth_server_types = { path = "../auth/types" }
social_server_types = { path = "../social/types" }

session_server_naia_proto = { path = "naia_proto" }
session_server_http_proto = { path = "http_proto" }
region_server_http_proto = { path = "../region/http_proto" }
asset_server_http_proto = { path = "../asset/http_proto" }
social_server_http_proto = { path = "../social/http_proto" }
auth_server_http_proto = { path = "../auth/http_proto" }

# These are the official Bevy crates, we can use them because the Server isn't built for Wasm
bevy_app = { version = "0.15", default-features=false }
bevy_ecs = { version = "0.15", default-features=false }

# TODO: remove this once bevy_log is updates the underlying tracing-log requirement from 0.1.2 to 0.2.0
regex = { version = "1.10.3", features = ["unicode-case"] }

cfg-if = { version = "1.0" }
